// Auto-generated by CRAFT Platform
// This file will be customized during deployment

export const config = {
    branding: {
        appName: process.env.NEXT_PUBLIC_APP_NAME || 'Stellar DEX',
        primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '#4f9eff',
        secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || '#1a1f36',
    },
    stellar: {
        network: process.env.NEXT_PUBLIC_STELLAR_NETWORK as 'mainnet' | 'testnet' || 'testnet',
        horizonUrl: process.env.NEXT_PUBLIC_HORIZON_URL || 'https://horizon-testnet.stellar.org',
        networkPassphrase: process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015',
    },
    features: {
        enableCharts: process.env.NEXT_PUBLIC_ENABLE_CHARTS === 'true',
        enableTransactionHistory: process.env.NEXT_PUBLIC_ENABLE_TRANSACTION_HISTORY === 'true',
        enableAnalytics: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS === 'true',
    },
} as const;

export default config;
