// Auto-generated by CRAFT Platform

export const config = {
    branding: {
        appName: process.env.NEXT_PUBLIC_APP_NAME || 'Soroban DeFi',
        primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '#4f9eff',
        secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || '#1a1f36',
    },
    stellar: {
        network: process.env.NEXT_PUBLIC_STELLAR_NETWORK as 'mainnet' | 'testnet' || 'testnet',
        horizonUrl: process.env.NEXT_PUBLIC_HORIZON_URL || 'https://horizon-testnet.stellar.org',
        sorobanRpcUrl: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org',
        networkPassphrase: process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015',
    },
    contracts: {
        // Contract addresses will be injected here
    },
} as const;

export default config;
